  - title: "Application"
    variables:
      - application_name
      - nb_copies
      - application_source
      - application_type
      - devops_compartment
      - repo_name
      - branch
      - build_command
      - artifact_location
      - registry_id
      - artifact_id
      - image_path
      - exposed_port
