name: 'Test appstack'
on: 
  workflow_dispatch:
    inputs:
      branch: 
        description: Branch name
        required: true
        default: 'main'
        type: string
      type: 
        description: Stack type
        required: true
        default: 'java'
        type: string
jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{github.ref_name}}
      type: 'java'
  build:
    needs: call-workflow-passing-data
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - name: upload-artifact
        uses: actions/download-artifact@v2
        with:
          name: appstackfor${{ inputs.type }}
          path: ./test/appstackfor${{ inputs.type }}.zip
      - name: run-test
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '11'
        env:
          OCI_PRIVATE_KEY_PEM: ${{ secrets.OCI_PRIVATE_KEY_PEM }}          
      - run: |
          cd test
          java -jar appstack-test.jar appstackfor${{ inputs.type }}.zip input.json
